<div>
    <!-- Well begun is half done. - Aristotle -->
    <table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <td>DanDanDan</td>
    <td>Shoto</td>
    <td>JJK</td>
  </tr>
  <tr>
    <td>Bleasch</td>
    <td>RAh</td>
    <td>Mexico</td>
  </tr>
</table>
</div>
